import type { Vault, UserPortfolio } from "@/types/vault";

export const MOCK_VAULTS: Vault[] = [
  {
    id: "aave-usdc-mainnet",
    name: "USDC Lending",
    protocol: "Aave V3",
    asset: "USD Coin",
    assetSymbol: "USDC",
    assetIcon: "https://cryptologos.cc/logos/usd-coin-usdc-logo.svg?v=025",
    network: "Ethereum",
    networkIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    tvlUsd: 248_500_000,
    supplyApy: 5.42,
    rewardApy: 1.18,
    totalApy: 6.6,
    utilization: 74.2,
    status: "active",
    contractAddress: "0xBcca60bB61934080951369a648Fb03DF4F96263C",
    userDepositUsd: 12_500,
    userDepositAmount: 12_500,
    earnedUsd: 142.3,
  },
  {
    id: "aave-weth-mainnet",
    name: "WETH Lending",
    protocol: "Aave V3",
    asset: "Wrapped Ether",
    assetSymbol: "WETH",
    assetIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    network: "Ethereum",
    networkIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    tvlUsd: 312_000_000,
    supplyApy: 3.15,
    rewardApy: 0.85,
    totalApy: 4.0,
    utilization: 68.5,
    status: "active",
    contractAddress: "0x030bA81f1c18d280636F32af80b9AAd02Cf0854e",
    userDepositUsd: 8_200,
    userDepositAmount: 2.45,
    earnedUsd: 67.8,
  },
  {
    id: "compound-usdt-mainnet",
    name: "USDT Lending",
    protocol: "Compound V3",
    asset: "Tether USD",
    assetSymbol: "USDT",
    assetIcon: "https://cryptologos.cc/logos/tether-usdt-logo.svg?v=025",
    network: "Ethereum",
    networkIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    tvlUsd: 98_400_000,
    supplyApy: 4.88,
    rewardApy: 0.62,
    totalApy: 5.5,
    utilization: 61.3,
    status: "active",
    contractAddress: "0x3Afdc9BCA9213A35503b077a6072F3D0d5AB0840",
  },
  {
    id: "morpho-wbtc-mainnet",
    name: "WBTC Vault",
    protocol: "Morpho Blue",
    asset: "Wrapped Bitcoin",
    assetSymbol: "WBTC",
    assetIcon: "https://cryptologos.cc/logos/wrapped-bitcoin-wbtc-logo.svg?v=025",
    network: "Ethereum",
    networkIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    tvlUsd: 67_200_000,
    supplyApy: 2.3,
    rewardApy: 0.45,
    totalApy: 2.75,
    utilization: 52.8,
    status: "active",
    contractAddress: "0x9ff58f4fFB29fA2266Ab25e75e2A8b3503311656",
  },
  {
    id: "yearn-dai-mainnet",
    name: "DAI Vault",
    protocol: "Yearn V3",
    asset: "Dai Stablecoin",
    assetSymbol: "DAI",
    assetIcon: "https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=025",
    network: "Ethereum",
    networkIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    tvlUsd: 124_800_000,
    supplyApy: 6.71,
    rewardApy: 1.94,
    totalApy: 8.65,
    utilization: 83.1,
    status: "active",
    contractAddress: "0xdA816459F1AB5631232FE5e97a05BBBb94970c95",
  },
  {
    id: "aave-usdc-arbitrum",
    name: "USDC Lending",
    protocol: "Aave V3",
    asset: "USD Coin",
    assetSymbol: "USDC",
    assetIcon: "https://cryptologos.cc/logos/usd-coin-usdc-logo.svg?v=025",
    network: "Arbitrum",
    networkIcon: "https://cryptologos.cc/logos/arbitrum-arb-logo.svg?v=025",
    tvlUsd: 89_300_000,
    supplyApy: 7.12,
    rewardApy: 2.35,
    totalApy: 9.47,
    utilization: 79.4,
    status: "active",
    contractAddress: "0x625E7708f30cA75bfd92586e17077590C60eb4cD",
  },
  {
    id: "euler-wsteth-mainnet",
    name: "wstETH Vault",
    protocol: "Euler V2",
    asset: "Wrapped stETH",
    assetSymbol: "wstETH",
    assetIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    network: "Ethereum",
    networkIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    tvlUsd: 45_600_000,
    supplyApy: 3.82,
    rewardApy: 0.73,
    totalApy: 4.55,
    utilization: 47.6,
    status: "active",
    contractAddress: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
  },
  {
    id: "spark-sdai-mainnet",
    name: "sDAI Savings",
    protocol: "Spark Protocol",
    asset: "Savings DAI",
    assetSymbol: "sDAI",
    assetIcon: "https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=025",
    network: "Ethereum",
    networkIcon: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=025",
    tvlUsd: 218_900_000,
    supplyApy: 8.0,
    rewardApy: 0.0,
    totalApy: 8.0,
    utilization: 100,
    status: "active",
    contractAddress: "0x83F20F44975D03b1b09e64809B757c47f942BEeA",
  },
];

export const MOCK_PORTFOLIO: UserPortfolio = {
  totalDepositedUsd: 20_700,
  totalEarnedUsd: 210.1,
  netApy: 5.71,
  activeVaults: 2,
};

export const TOTAL_STATS = {
  totalTvlUsd: MOCK_VAULTS.reduce((s, v) => s + v.tvlUsd, 0),
  totalVaults: MOCK_VAULTS.length,
  avgApy:
    MOCK_VAULTS.reduce((s, v) => s + v.totalApy, 0) / MOCK_VAULTS.length,
};
