# ──────────────────────────────────────────────────────────────────────────────
# Multi-stage Dockerfile for OpenVault (Next.js 16, pnpm, Node 20 LTS)
#
# Stages:
#   base    — Node 20 Alpine + pnpm
#   deps    — Install production + dev dependencies
#   builder — Build the Next.js app (output: standalone)
#   runner  — Minimal runtime image (~no node_modules)
#
# Build-time variables (NEXT_PUBLIC_* are baked into the client bundle):
#   docker build \
#     --build-arg NEXT_PUBLIC_REOWN_PROJECT_ID=... \
#     --build-arg NEXT_PUBLIC_ULTRAYIELD_VAULT_ADDR=... \
#     --build-arg NEXT_PUBLIC_MORPHO_VAULT_ADDR=... \
#     --build-arg NEXT_PUBLIC_APP_URL=https://your-domain.com \
#     -t openvault .
#
# Runtime variables (pass to container via -e or --env-file):
#   REDIS_URL, RPC_URL_1, RPC_URL_8453, RATE_LIMIT_ENABLED,
#   ONEINCH_API_KEY, ONECLICK_JWT_TOKEN
# ──────────────────────────────────────────────────────────────────────────────

# ── Stage 1: base ─────────────────────────────────────────────────────────────
FROM node:20-alpine AS base
# Enable corepack and pin pnpm to the same version used in development
RUN corepack enable && corepack prepare pnpm@11.1.3 --activate

# ── Stage 2: deps ─────────────────────────────────────────────────────────────
FROM base AS deps
WORKDIR /app

# Copy package manifests and pnpm config first (layer cache for installs)
COPY package.json pnpm.json ./
# Copy lockfile if present; pnpm will generate one otherwise
COPY pnpm-lock.yaml* ./

# Install all dependencies (dev deps needed for the build step)
RUN pnpm install --frozen-lockfile 2>/dev/null || pnpm install

# ── Stage 3: builder ──────────────────────────────────────────────────────────
FROM base AS builder
WORKDIR /app

# ── Build-time env vars (NEXT_PUBLIC_* are inlined into the JS bundle) ────────
ARG NEXT_PUBLIC_REOWN_PROJECT_ID
ARG NEXT_PUBLIC_ULTRAYIELD_VAULT_ADDR
ARG NEXT_PUBLIC_ULTRAYIELD_CHAIN_ID=1
ARG NEXT_PUBLIC_MORPHO_VAULT_ADDR
ARG NEXT_PUBLIC_MIDAS_VAULT_ADDR
ARG NEXT_PUBLIC_MIDAS_CHAIN_ID=1
ARG NEXT_PUBLIC_SWAP_MIN_USD=5
ARG NEXT_PUBLIC_APP_URL

ENV NEXT_PUBLIC_REOWN_PROJECT_ID=$NEXT_PUBLIC_REOWN_PROJECT_ID
ENV NEXT_PUBLIC_ULTRAYIELD_VAULT_ADDR=$NEXT_PUBLIC_ULTRAYIELD_VAULT_ADDR
ENV NEXT_PUBLIC_ULTRAYIELD_CHAIN_ID=$NEXT_PUBLIC_ULTRAYIELD_CHAIN_ID
ENV NEXT_PUBLIC_MORPHO_VAULT_ADDR=$NEXT_PUBLIC_MORPHO_VAULT_ADDR
ENV NEXT_PUBLIC_MIDAS_VAULT_ADDR=$NEXT_PUBLIC_MIDAS_VAULT_ADDR
ENV NEXT_PUBLIC_MIDAS_CHAIN_ID=$NEXT_PUBLIC_MIDAS_CHAIN_ID
ENV NEXT_PUBLIC_SWAP_MIN_USD=$NEXT_PUBLIC_SWAP_MIN_USD
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
# Suppress Next.js telemetry during CI/CD builds
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN pnpm build

# ── Stage 4: runner ───────────────────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Port the app listens on (matches `next start -p 3032`)
ENV PORT=3032
ENV HOSTNAME=0.0.0.0

# Run as a non-root user for security
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy the standalone server bundle produced by `output: "standalone"`
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static assets (standalone does not include these automatically)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3032

# server.js is the entry point generated by Next.js standalone output
CMD ["node", "server.js"]
